[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wallet_program = "2fJd8iYjyi3FhCWYWARMdjBmqKHX8RnjyJpM7FgkWtiw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sks123456/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
